export const genres = {
  acoustic: "acoustic",
  afrobeat: "afrobeat",
  altRock: "alt-rock",
  alternative: "alternative",
  ambient: "ambient",
  anime: "anime",
  blackMetal: "black-metal",
  bluegrass: "bluegrass",
  blues: "blues",
  bossanova: "bossanova",
  brazil: "brazil",
  breakbeat: "breakbeat",
  british: "british",
  cantopop: "cantopop",
  chicagoHouse: "chicago-house",
  children: "children",
  chill: "chill",
  classical: "classical",
  club: "club",
  comedy: "comedy",
  country: "country",
  dance: "dance",
  dancehall: "dancehall",
  deathMetal: "death-metal",
  deepHouse: "deep-house",
  detroitTechno: "detroit-techno",
  disco: "disco",
  disney: "disney",
  drumAndBass: "drum-and-bass",
  dub: "dub",
  dubstep: "dubstep",
  edm: "edm",
  electro: "electro",
  electronic: "electronic",
  emo: "emo",
  folk: "folk",
  forro: "forro",
  french: "french",
  funk: "funk",
  garage: "garage",
  german: "german",
  gospel: "gospel",
  goth: "goth",
  grindcore: "grindcore",
  groove: "groove",
  grunge: "grunge",
  guitar: "guitar",
  happy: "happy",
  hardRock: "hard-rock",
  hardcore: "hardcore",
  hardstyle: "hardstyle",
  heavyMetal: "heavy-metal",
  hipHop: "hip-hop",
  holidays: "holidays",
  honkyTonk: "honky-tonk",
  house: "house",
  idm: "idm",
  indian: "indian",
  indie: "indie",
  indiePop: "indie-pop",
  industrial: "industrial",
  iranian: "iranian",
  jDance: "j-dance",
  jIdol: "j-idol",
  jPop: "j-pop",
  jRock: "j-rock",
  jazz: "jazz",
  kPop: "k-pop",
  kids: "kids",
  latin: "latin",
  latino: "latino",
  malay: "malay",
  mandopop: "mandopop",
  metal: "metal",
  metalMisc: "metal-misc",
  metalCore: "metalcore",
  minimalTechno: "minimal-techno",
  movies: "movies",
  mpb: "mpb",
  newAge: "new-age",
  newRelease: "new-release",
  opera: "opera",
  pagode: "pagode",
  party: "party",
  philippinesOpm: "philippines-opm",
  piano: "piano",
  pop: "pop",
  popFilm: "pop-film",
  postDubstep: "post-dubstep",
  powerPop: "power-pop",
  progressiveHouse: "progressive-house",
  psychRock: "psych-rock",
  punk: "punk",
  punkRock: "punk-rock",
  rnb: "r-n-b",
  rainyDay: "rainy-day",
  reggae: "reggae",
  reggaeton: "reggaeton",
  roatTrip: "road-trip",
  rock: "rock",
  rockNRoll: "rock-n-roll",
  rockabilly: "rockabilly",
  romance: "romance",
  sad: "sad",
  salsa: "salsa",
  samba: "samba",
  sertanejo: "sertanejo",
  showTunes: "show-tunes",
  singerSongwriter: "singer-songwriter",
  ska: "ska",
  sleep: "sleep",
  songwriter: "songwriter",
  soul: "soul",
  soundtracks: "soundtracks",
  spanish: "spanish",
  study: "study",
  summer: "summer",
  swedish: "swedish",
  synthPop: "synth-pop",
  tango: "tango",
  techno: "techno",
  trance: "trance",
  tripHop: "trip-hop",
  turkish: "turkish",
  workOut: "work-out",
  worldMusic: "world-music",
};

export const genreList = [
  genres.pop,
  genres.hipHop,
  genres.dance,
  genres.rock,
  genres.country,
  genres.classical,
  genres.rnb,
  genres.metal,
  genres.anime,
  genres.alternative,
  genres.kPop,
  genres.reggae,
  genres.piano,
  genres.jazz,
  genres.jPop,
  genres.latin,
];
